const TRANSLATIONS = {
  fr: {
    "nav.about": "À propos",
    "nav.experience": "Expérience",
    "nav.projects": "Projets",
    "nav.gallery": "Galerie",
    "nav.contact": "Contact",
    "cta.download": "Télécharger CV",
    "about.title": "UNE ÉTUDIANTE VIETNAMIENNE EN FRANCE",
    "about.name": "NGUYEN Thi To Tam",
    "about.education": "FORMATION",
    "about.years1": "2024 — 2026",
    "about.years2": "2020 — 2022",
    "about.years3": "2019 — 2020",
    "about.years4": "2017 — 2019",
    "about.school1": "Université Gustave Eiffel",
    "about.school2": "Université Gustave Eiffel",
    "about.school3": "Université Cote d'Azur",
    "about.school4": "IUT Robert Schuman",
    "about.degree1": "Master Cultures et Métiers du web",
    "about.degree2":
      "Master Intelligence économique option Influence, Lobbying et Médias sociaux",
    "about.degree3": "Licence Communication audio-visuelle",
    "about.degree4":
      "DUT Information- Communication option Communication des organisations",
    "about.description1":
      "Communications specialist - Content Writer - Conceptrice interactive",
    "about.description2":
      "Je suis un étudiant en dernière année du Master Cultures et métiers du web, spécialisé dans l'intersection entre le documentaire et les interfaces interactives. Mon travail vise à simplifier le complexe et à mettre en lumière ce qui est souvent négligé.",
    "exp.title": "CARRIÈRE",
    "exp.subtitle": "Expérience professionnelle",
    "exp.type1": "ALTERNANCE",
    "exp.type2": "STAGE",
    "exp.name1": "Digital Communication Officer",
    "exp.description1":
      "Déploiement de stratégies marketing multicanal et gestion de contenu e-commerce (PrestaShop). Création et optimisation d'actifs numériques, suivi des KPI et recommandations UX pour améliorer les parcours utilisateurs.",
    "exp.more1-1": "Digital Communication Officer (apprenticeship).",
    "exp.more1-2":
      "Deployed multi-channel marketing strategies and managed e-commerce content (PrestaShop).",
    "exp.more1-3":
      "Created and optimized digital assets, monitored KPIs, and delivered UX recommendations to enhance user journeys.",
    "exp.years1": "2022 — Présent",
    "project.title": "CRÉATION NUMÉRIQUE",
    "project.subtitle": "Projets sélectionnés",
    "project.name1": "Vivre sans les Chaebols",
    "project.type1": "DOCUMENTAIRE / WEB INTERACTIF",
    "project.description1":
      "Conception d'un web-documentaire majeur (Master M2). En charge de la recherche documentaire thématique et de la rédaction globale des contenus du site interactif.",
    "gallery.title": "ÉTUDES VISUELLES",
    "gallery.subtitle": "Albums photo",
    "gallery.album1": "Pigeons dans le jardin",
    "gallery.year1": "2022",
    "gallery.album2": "Chats dans le jardin",
    "gallery.year2": "2023",
    "contact.title": "CONTACT",
    "contact.subtitle": "Mon profil vous intéresse ? Discutons-en !",
    "contact.email": "nguyenthitotam98@gmail.com",
    "contact.social": "Réseaux sociaux",
    "contact.linkedin": "LinkedIn",
    "contact.location": "Localisation",
    "contact.city1": "Paris, France",
    "contact.city2": "Hanoi, Vietnam",
    "footer.text": "© 2026 NGUYEN Thi To Tam. Tous droits réservés.",
  },
  en: {
    "nav.about": "About",
    "nav.experience": "Experience",
    "nav.projects": "Projects",
    "nav.gallery": "Gallery",
    "nav.contact": "Contact",
    "cta.download": "Download CV",
    "about.title": "A VIETNAMESE STUDENT IN FRANCE",
    "about.name": "NGUYEN Thi To Tam",
    "about.education": "EDUCATION",
    "about.years1": "2024 — 2026",
    "about.years2": "2020 — 2022",
    "about.years3": "2019 — 2020",
    "about.years4": "2017 — 2019",
    "about.school1": "Gustave Eiffel University",
    "about.school2": "Gustave Eiffel University",
    "about.school3": "Cote d'Azur University",
    "about.school4": "IUT Robert Schuman",
    "about.degree1": "Master's Degree in Web Culture and Digital",
    "about.degree2":
      "Master's Degree in Economic Intelligence specialization in Influence, Lobbying and Social Media",
    "about.degree3": "Bachelor's Degree in Audiovisual Communication",
    "about.degree4": "DUT Corporate & Organizational Communication",
    "about.description1":
      "Communications specialist - Content Writer - Conceptrice interactive",
    "about.description2":
      "I am a final-year Master's student in Web Cultures and Professions, specializing in the intersection of documentary and interactive interfaces. My work aims to simplify the complex and shed light on what is often overlooked.",
    "exp.title": "CAREER",
    "exp.subtitle": "Professional Experience",
    "exp.type1": "APPRENTICESHIP",
    "exp.type2": "INTERNSHIP",
    "exp.name1": "Digital Communication Officer",
    "exp.description1":
      "Deployed multi-channel marketing strategies and managed e-commerce content (PrestaShop). Created and optimized digital assets, monitored KPIs, and delivered UX recommendations to enhance user journeys.",
    "exp.more1-1": "Digital Communication Officer (apprenticeship).",
    "exp.more1-2":
      "Deployed multi-channel marketing strategies and managed e-commerce content (PrestaShop).",
    "exp.more1-3":
      "Created and optimized digital assets, monitored KPIs, and delivered UX recommendations to enhance user journeys.",
    "exp.years1": "2022 — Present",
    "project.title": "DIGITAL CREATION",
    "project.subtitle": "Selected Projects",
    "project.name1": "Living without the Chaebols",
    "project.type1": "DOCUMENTARY / INTERACTIVE WEBSITE",
    "project.description1":
      "Designed a major web-documentary (Master M2). Responsible for thematic documentary research and overall content writing for the interactive website.",
    "gallery.title": "VISUAL STUDIES",
    "gallery.subtitle": "Photo Albums",
    "gallery.album1": "Pigeons in the garden",
    "gallery.year1": "2022",
    "gallery.album2": "Cats in the garden",
    "gallery.year2": "2023",
    "contact.title": "CONTACT",
    "contact.subtitle": "Interested in my profile? Let's talk!",
    "contact.email": "nguyenthitotam98@gmail.com",
    "contact.social": "Social",
    "contact.linkedin": "LinkedIn",
    "contact.location": "Location",
    "contact.city1": "Paris, France",
    "contact.city2": "Hanoi, Vietnam",
    "footer.text": "© 2026 NGUYEN Thi To Tam. All rights reserved.",
  },
};

const PROJECT_ITEMS = [
  {
    name: "project.name1",
    type: "project.type1",
    description: "project.description1",
  },
];
